---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "gateway.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.labels }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: istio
  addresses:
    - type: Hostname
      value: {{ include "gateway.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
